runtime: python
env: flex
entrypoint: gunicorn -b :$PORT less0n:app
api_version: 1
threadsafe: true

runtime_config:
  python_version: 3

# [START handlers]
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: less0n.app
# [END handlers]

# This sample incurs costs to run on the App Engine flexible environment. 
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
